start_shard_index: ???
end_shard_index: ???
task_id: ???
shards_per_node_batch: 100
overwrite: False
batch_size: 64  # 64 for maxvit, 256 for effnetb0
num_workers: 10
devices: 1
accelerator: gpu
precision: '16-mixed'