start_shard_index: 0
# end_shard_index: 20
end_shard_index: 5000
task_id: 42
shards_per_node_batch: 10 
overwrite: False
batch_size: 256   # nano, 24gb mem on L4
num_workers: 32  # loads of cores :)
devices: 1
accelerator: gpu
precision: '16-mixed'