start_snippet_index: ???
end_snippet_index: ???
task_id: ???
snippets_per_node_batch: 20
overwrite: False
batch_size: 64  # 64 for maxvit, 256 for effnetb0
num_workers: 10
devices: 1
accelerator: gpu
